-- CreateEnum
CREATE TYPE "UserAction" AS ENUM ('CHECK_OUT_CONTENT', 'CHECK_IN_CONTENT', 'EDIT_TITLE', 'TRANSFER_OWNERSHIP', 'EDIT_LAST_MODIFIED_DATE', 'EDIT_EXPIRATION_DATE', 'EDIT_CONTENT_STATUS', 'EDIT_CONTENT_TAGS', 'REUPLOAD_FILE', 'EDIT_LINK', 'CREATE_DISCUSSION', 'COMMENT', 'VIEW_CONTENT', 'DOWNLOAD_FILE', 'DELETE_CONTENT', 'UPLOAD_CONTENT', 'EDIT_AVATAR', 'EDIT_PROFILE');

-- CreateTable
CREATE TABLE "ActivityLog" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "action" "UserAction" NOT NULL,
    "contentId" TEXT,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ActivityLog_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ActivityLog" ADD CONSTRAINT "ActivityLog_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ActivityLog" ADD CONSTRAINT "ActivityLog_contentId_fkey" FOREIGN KEY ("contentId") REFERENCES "Content"("id") ON DELETE SET NULL ON UPDATE CASCADE;
