export const UserAction = {
	CHECK_OUT_CONTENT: "CHECK_OUT_CONTENT",
	CHECK_IN_CONTENT: "CHECK_IN_CONTENT",
	EDIT_TITLE: "EDIT_TITLE",
	TRANSFER_OWNERSHIP: "TRANSFER_OWNERSHIP",
	EDIT_LAST_MODIFIED_DATE: "EDIT_LAST_MODIFIED_DATE",
	EDIT_EXPIRATION_DATE: "EDIT_EXPIRATION_DATE",
	EDIT_CONTENT_STATUS: "EDIT_CONTENT_STATUS",
	EDIT_CONTENT_TAGS: "EDIT_CONTENT_TAGS",
	REUPLOAD_FILE: "REUPLOAD_FILE",
	EDIT_LINK: "EDIT_LINK",
	CREATE_DISCUSSION: "CREATE_DISCUSSION",
	COMMENT: "COMMENT",
	VIEW_CONTENT: "VIEW_CONTENT",
	DOWNLOAD_FILE: "DOWNLOAD_FILE",
	DELETE_CONTENT: "DELETE_CONTENT",
	UPLOAD_CONTENT: "UPLOAD_CONTENT",
	EDIT_AVATAR: "EDIT_AVATAR",
	EDIT_PROFILE: "EDIT_PROFILE",
} as const

export type UserAction = (typeof UserAction)[keyof typeof UserAction]

export const activityLabelToStringTable: Record<UserAction, string> = {
	CHECK_OUT_CONTENT: "Content checked out",
	CHECK_IN_CONTENT: "Content checked in",
	EDIT_TITLE: "Title edited",
	TRANSFER_OWNERSHIP: "Content ownership transferred",
	EDIT_LAST_MODIFIED_DATE: "Content last modified date edited",
	EDIT_EXPIRATION_DATE: "Content expiration date edited",
	EDIT_CONTENT_STATUS: "Content status changed",
	EDIT_CONTENT_TAGS: "Content tags changed",
	REUPLOAD_FILE: "File reuploaded",
	EDIT_LINK: "Link updated",
	CREATE_DISCUSSION: "Discussion started",
	COMMENT: "New comment",
	VIEW_CONTENT: "Content viewed",
	DOWNLOAD_FILE: "File downloaded",
	DELETE_CONTENT: "Content deleted",
	UPLOAD_CONTENT: "Content uploaded",
	EDIT_AVATAR: "User avatar updated",
	EDIT_PROFILE: "User profile updated",
}

export const activityLabelToStringTimeline: Record<UserAction, string> = {
	CHECK_OUT_CONTENT: "Checked Out",
	CHECK_IN_CONTENT: "Checked In",
	EDIT_TITLE: "Content Edited",
	TRANSFER_OWNERSHIP: "Ownership Transferred",
	EDIT_LAST_MODIFIED_DATE: "Content Edited",
	EDIT_EXPIRATION_DATE: "Content Edited",
	EDIT_CONTENT_STATUS: "Content Edited",
	EDIT_CONTENT_TAGS: "Content Edited",
	REUPLOAD_FILE: "Content Edited",
	EDIT_LINK: "Content Edited",
	CREATE_DISCUSSION: "Comment Created",
	COMMENT: "Comment Created",
	VIEW_CONTENT: "Viewed Content",
	DOWNLOAD_FILE: "Downloaded Content",
	DELETE_CONTENT: "Deleted Content",
	UPLOAD_CONTENT: "Uploaded Content",
	EDIT_AVATAR: "Profile Updated",
	EDIT_PROFILE: "Profile Updated",
}
