import { ContentStatus, ContentType, type Prisma } from "../../server/generated/prisma/client.ts"
import { randomUserId } from "./users.ts"

export const linkContentData = [
	...[
		{
			title: "Risk Meter",
			description: "",
			url: "https://riskmeter.corelogic.com/",
			lastModifiedDate: new Date("2026-03-27"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Image Editor",
			description: "",
			url: "https://www.adobe.com/express/feature/image/editor",
			lastModifiedDate: new Date("2025-10-26"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Underwriter Workstation",
			description: "",
			url: "https://drive.google.com/drive/my-drive",
			lastModifiedDate: new Date("2025-07-13"),
			expirationDate: new Date("2026-06-15"),
			status: ContentStatus.Incomplete,
		},
		{
			title: "Document Signing",
			description: "",
			url: "https://www.docusign.com/",
			lastModifiedDate: new Date("2025-11-01"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Desktop Management Tool",
			description: "",
			url: "https://www.teamviewer.com/en-us/",
			lastModifiedDate: new Date("2025-09-15"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.Incomplete,
		},
		{
			title: "Process Automation Tool",
			description: "",
			url: "https://www.flowforma.com/",
			lastModifiedDate: new Date("2025-08-20"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Knowledge Base",
			description: "",
			url: "https://www.genre.com/us/knowledge?filters=article-type:publication,genre-languages:en&page=1&facet=all",
			lastModifiedDate: new Date("2025-10-05"),
			expirationDate: new Date("2026-10-01"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Flood Information",
			description: "",
			url: "https://msc.fema.gov/portal/home",
			lastModifiedDate: new Date("2025-09-10"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.Complete,
		},
		{
			title: "OSHA Regulations",
			description: "",
			url: "https://www.osha.gov/laws-regs",
			lastModifiedDate: new Date("2025-11-20"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Pennsylvania Schedule Rating Plan",
			description: "",
			url: "https://pcrb.com/industry-reports/schedule-rating-plan/",
			lastModifiedDate: new Date("2025-08-05"),
			expirationDate: new Date("2026-10-01"),
			status: ContentStatus.Incomplete,
		},
		{
			title: "Kentucky Tax Law",
			description: "",
			url: "https://revenue.ky.gov/Get-Help/pages/research-tax-laws.aspx",
			lastModifiedDate: new Date("2026-02-04"),
			expirationDate: new Date("2026-04-15"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Oregon Tax Law",
			description: "",
			url: "https://www.oregon.gov/dor/pages/rules-laws.aspx",
			lastModifiedDate: new Date("2025-12-12"),
			expirationDate: new Date("2026-04-15"),
			status: ContentStatus.Complete,
		},
		{
			title: "States on Hold",
			description: "",
			url: "https://www.policygenius.com/homeowners-insurance/home-insurance-availability-guide-states-crisis/",
			lastModifiedDate: new Date("2025-11-15"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Error Lookup Tool",
			description: "",
			url: "https://www.google.com/",
			lastModifiedDate: new Date("2025-10-01"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Incomplete,
		},
		{
			title: "Workflow Management Platform",
			description: "",
			url: "https://monday.com/",
			lastModifiedDate: new Date("2025-09-20"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Claim Search",
			description: "",
			url: "https://claimsearch.iso.com/index.asp",
			lastModifiedDate: new Date("2025-08-10"),
			expirationDate: new Date("2026-12-31"),
		},
		{
			title: "Business Analyst Guide",
			description: "",
			url: "https://www.iiba.org/career-resources/a-business-analysis-professionals-foundation-for-success/babok/",
			lastModifiedDate: new Date("2025-07-01"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "State Research Guides",
			description: "",
			url: "https://www.namic.org/compliance/50-state-research-guides/",
			lastModifiedDate: new Date("2025-11-05"),
			expirationDate: new Date("2026-10-01"),
		},
		{
			title: "Policy Tracking Software",
			description: "",
			url: "https://www.agencybloc.com/",
			lastModifiedDate: new Date("2025-10-15"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "Latest Insurance News",
			description: "",
			url: "https://www.insurancejournal.com/",
			lastModifiedDate: new Date("2025-09-05"),
			expirationDate: new Date("2026-12-31"),
		},
		{
			title: "AM Best",
			description: "Insurance rating and information source.",
			url: "https://www.ambest.com/",
			lastModifiedDate: new Date("2026-01-10"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "Insurance Information Institute",
			description: "Trusted source of data-driven insights on insurance.",
			url: "https://www.iii.org/",
			lastModifiedDate: new Date("2026-02-15"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "National Association of Insurance Commissioners",
			description: "Standard-setting and regulatory support organization.",
			url: "https://content.naic.org/",
			lastModifiedDate: new Date("2026-03-01"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "American Property Casualty Insurance Association",
			description: "Advocacy for the property casualty insurance industry.",
			url: "https://www.apci.org/",
			lastModifiedDate: new Date("2025-12-05"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "ISO Community Hazard Mitigation",
			description: "Information on building codes and hazard mitigation.",
			url: "https://www.isomitigation.com/",
			lastModifiedDate: new Date("2026-01-20"),
			expirationDate: new Date("2026-12-31"),
		},
		{
			title: "National Flood Insurance Program (NFIP)",
			description: "Official site for the federal flood insurance program.",
			url: "https://www.floodsmart.gov/",
			lastModifiedDate: new Date("2026-02-10"),
			expirationDate: new Date("2027-02-01"),
		},
		{
			title: "Insurance Institute for Highway Safety (IIHS)",
			description: "Vehicle safety research and ratings.",
			url: "https://www.iihs.org/",
			lastModifiedDate: new Date("2026-03-05"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "Coalition Against Insurance Fraud",
			description: "Alliance fighting insurance fraud through advocacy.",
			url: "https://insurancefraud.org/",
			lastModifiedDate: new Date("2026-01-15"),
			expirationDate: new Date("2027-03-15"),
		},
		{
			title: "Council of Insurance Agents & Brokers (CIAB)",
			description:
				"Premier association for commercial insurance and employee benefits intermediaries.",
			url: "https://www.ciab.com/",
			lastModifiedDate: new Date("2025-11-20"),
			expirationDate: new Date("2026-12-31"),
		},
		{
			title: "The Geneva Association",
			description: "International insurance think tank addressing global risks.",
			url: "https://www.genevaassociation.org/",
			lastModifiedDate: new Date("2026-03-20"),
			expirationDate: new Date("2027-05-01"),
		},
		{
			title: "International Association of Insurance Supervisors (IAIS)",
			description: "Global standard-setting body for insurance supervisors.",
			url: "https://www.iaisweb.org/",
			lastModifiedDate: new Date("2026-02-28"),
			expirationDate: new Date("2027-01-31"),
		},
		{
			title: "Risk and Insurance Management Society (RIMS)",
			description: "Professional association dedicated to the advancement of risk management.",
			url: "https://www.rims.org/",
			lastModifiedDate: new Date("2026-01-10"),
			expirationDate: new Date("2027-02-15"),
		},
		{
			title: "Lloyd's of London",
			description: "The world's leading insurance and reinsurance marketplace.",
			url: "https://www.lloyds.com/",
			lastModifiedDate: new Date("2026-04-05"),
			expirationDate: new Date("2027-04-01"),
		},
		{
			title: "Workers Compensation Research Institute (WCRI)",
			description:
				"Nonprofit research organization generating factual information on workers' compensation systems.",
			url: "https://www.wcrinet.org/",
			lastModifiedDate: new Date("2025-12-12"),
			expirationDate: new Date("2026-12-31"),
		},
		{
			title: "National Council on Compensation Insurance (NCCI)",
			description: "Provider of workers compensation data, insights, and solutions.",
			url: "https://www.ncci.com/",
			lastModifiedDate: new Date("2026-01-18"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "Federal Emergency Management Agency (FEMA)",
			description: "Source for disaster guidelines, flood maps, and crisis response.",
			url: "https://www.fema.gov/",
			lastModifiedDate: new Date("2026-03-12"),
			expirationDate: new Date("2027-03-31"),
		},
		{
			title: "California Department of Insurance",
			description: "Regulatory body oversees the largest insurance market in the US.",
			url: "https://www.insurance.ca.gov/",
			lastModifiedDate: new Date("2026-02-22"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "New York State Department of Financial Services",
			description: "New York regulations and financial guidelines for insurers.",
			url: "https://www.dfs.ny.gov/",
			lastModifiedDate: new Date("2026-03-01"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "Texas Department of Insurance",
			description: "Regulatory resources and code guidance for Texas.",
			url: "https://www.tdi.texas.gov/",
			lastModifiedDate: new Date("2026-01-30"),
			expirationDate: new Date("2027-02-28"),
		},
		{
			title: "Casualty Actuarial Society (CAS)",
			description: "Credentialing and professional education for property and casualty actuaries.",
			url: "https://www.casact.org/",
			lastModifiedDate: new Date("2025-11-15"),
			expirationDate: new Date("2026-11-30"),
		},
		{
			title: "Society of Actuaries (SOA)",
			description: "Education and research spanning life, health, and property insurance.",
			url: "https://www.soa.org/",
			lastModifiedDate: new Date("2026-02-05"),
			expirationDate: new Date("2027-02-01"),
		},
		{
			title: "Swiss Re Institute",
			description: "Risk research and insights from one of the largest reinsurers.",
			url: "https://www.swissre.com/institute.html",
			lastModifiedDate: new Date("2026-03-22"),
			expirationDate: new Date("2027-06-01"),
		},
		{
			title: "Munich Re Risk Insights",
			description: "Global insurance insights, climate solutions, and emerging risk data.",
			url: "https://www.munichre.com/en/risks.html",
			lastModifiedDate: new Date("2026-01-05"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "Reinsurance Association of America (RAA)",
			description: "Advocacy and education organization for the US reinsurance industry.",
			url: "https://www.reinsurance.org/",
			lastModifiedDate: new Date("2026-02-14"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "Willis Towers Watson Insights",
			description: "Market outlooks and strategic insights on risk and broking.",
			url: "https://www.wtwco.com/en-US/Insights",
			lastModifiedDate: new Date("2026-04-10"),
			expirationDate: new Date("2027-05-31"),
		},
		{
			title: "Marsh McLennan Insights",
			description: "Analytics and thought leadership on managing complex risks.",
			url: "https://www.marshmclennan.com/insights.html",
			lastModifiedDate: new Date("2026-03-18"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "Aon Insights",
			description: "Advanced analytics and studies on enterprise risk management.",
			url: "https://www.aon.com/insights",
			lastModifiedDate: new Date("2026-02-25"),
			expirationDate: new Date("2027-03-01"),
		},
		{
			title: "Insurance Research Council (IRC)",
			description: "Independent organization providing public policy research to the P&C industry.",
			url: "https://www.insurance-research.org/",
			lastModifiedDate: new Date("2025-10-31"),
			expirationDate: new Date("2026-10-31"),
		},
		{
			title: "National Association of Mutual Insurance Companies (NAMIC)",
			description: "Advocacy and resources for mutual insurance organizations.",
			url: "https://www.namic.org/",
			lastModifiedDate: new Date("2026-01-08"),
			expirationDate: new Date("2027-01-01"),
		},
		{
			title: "ISO Circular Library",
			description: "",
			url: "https://www.verisk.com/insurance/brands/iso/",
			lastModifiedDate: new Date("2025-10-12"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "NCCI Manuals",
			description: "",
			url: "https://www.ncci.com/Articles/Pages/II_Manuals-Overview.aspx",
			lastModifiedDate: new Date("2025-09-01"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Catastrophe Risk Portal",
			description: "",
			url: "https://www.air-worldwide.com/",
			lastModifiedDate: new Date("2025-11-10"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Reinsurance Treaty Database",
			description: "",
			url: "https://www.swissre.com/",
			lastModifiedDate: new Date("2025-08-22"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Property Loss Estimator",
			description: "",
			url: "https://www.corelogic.com/",
			lastModifiedDate: new Date("2025-10-30"),
			expirationDate: new Date("2026-10-01"),
			status: ContentStatus.Incomplete,
		},
		{
			title: "Actuarial Standards Board",
			description: "",
			url: "https://www.actuarialstandardsboard.org/",
			lastModifiedDate: new Date("2025-07-15"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Insurance Fraud Bureau",
			description: "",
			url: "https://www.insurancefraud.org/",
			lastModifiedDate: new Date("2025-09-25"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Commercial Lines Manual",
			description: "",
			url: "https://www.irmi.com/",
			lastModifiedDate: new Date("2025-11-01"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Weather Risk Analytics",
			description: "",
			url: "https://www.tomorrow.io/",
			lastModifiedDate: new Date("2025-08-14"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.Incomplete,
		},
		{
			title: "Surplus Lines Filing System",
			description: "",
			url: "https://www.stampsurplus.com/",
			lastModifiedDate: new Date("2025-10-08"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Process Mapping Tool",
			description: "",
			url: "https://www.lucidchart.com/",
			lastModifiedDate: new Date("2025-10-20"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Requirements Management",
			description: "",
			url: "https://www.jama.com/",
			lastModifiedDate: new Date("2025-09-14"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Data Dictionary Portal",
			description: "",
			url: "https://www.dataedo.com/",
			lastModifiedDate: new Date("2025-08-30"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Stakeholder Communication Hub",
			description: "",
			url: "https://www.confluence.atlassian.com/",
			lastModifiedDate: new Date("2025-11-05"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Incomplete,
		},
		{
			title: "Insurance Regulatory Database",
			description: "",
			url: "https://content.naic.org/",
			lastModifiedDate: new Date("2025-07-20"),
			expirationDate: new Date("2026-10-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Market Analysis Platform",
			description: "",
			url: "https://www.ibisworld.com/",
			lastModifiedDate: new Date("2025-10-02"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Compliance Tracker",
			description: "",
			url: "https://www.vericast.com/",
			lastModifiedDate: new Date("2025-09-18"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Business Intelligence Dashboard",
			description: "",
			url: "https://www.tableau.com/",
			lastModifiedDate: new Date("2025-08-07"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "User Story Mapping",
			description: "",
			url: "https://storiesonboard.com/",
			lastModifiedDate: new Date("2025-11-22"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.Incomplete,
		},
		{
			title: "API Documentation Hub",
			description: "",
			url: "https://swagger.io/",
			lastModifiedDate: new Date("2025-07-10"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Insurance Industry News",
			description: "",
			url: "https://www.propertycasualty360.com/",
			lastModifiedDate: new Date("2025-10-25"),
			expirationDate: new Date("2026-10-01"),
			status: ContentStatus.UnderReview,
		},
		{
			title: "Gap Analysis Framework",
			description: "",
			url: "https://www.smartsheet.com/",
			lastModifiedDate: new Date("2025-09-03"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
		{
			title: "Customer Journey Mapping",
			description: "",
			url: "https://www.miro.com/",
			lastModifiedDate: new Date("2025-08-19"),
			expirationDate: new Date("2026-12-31"),
			status: ContentStatus.Incomplete,
		},
		{
			title: "Regulatory Change Monitor",
			description: "",
			url: "https://www.wolterskluwer.com/en/solutions/oneshield",
			lastModifiedDate: new Date("2025-11-08"),
			expirationDate: new Date("2027-01-01"),
			status: ContentStatus.Complete,
		},
	].map((content) => ({
		...content,
		type: ContentType.Link,
		ownerId: randomUserId(),
		createdAt: content.lastModifiedDate,
	})),
] satisfies Prisma.ContentCreateManyInput[]
